# Generated by Django 6.0.2 on 2026-02-28 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=30)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=255)),
                ('job_title', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=100)),
                ('resume', models.FileField(blank=True, null=True, upload_to='uploads/resumes/')),
                ('national_id', models.FileField(blank=True, null=True, upload_to='uploads/national_ids/')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='uploads/photos/')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
