# Generated by Django 6.0.2 on 2026-02-28 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerWarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('high', 'High Priority'), ('normal', 'Normal')], default='normal', max_length=10)),
                ('sent_by', models.CharField(default='Admin', max_length=100)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warnings', to='main.userprofile')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
